### ISSUE TITLE
Starting/Ending Point Fixing

### ISSUE THREAD

**Issue by MrR0b0t14** [Werocky/se2022-01-HikeTracker#17]
I would like you to fix the problem in selecting different Starting and Ending Points about the hike.
Very grateful for your work!

**Comment by DavideBrl** [comment]
Now a local guide can modify the starting/ending point of an hike by selecting a point on the path (click on the map). If the guide wants to select a point close to the route, the system automatically takes the point closest to it.
Note that the same thing can also be done for other points that are not start or end points.
